#!/usr/bin/env python3
"""c2sql-gen — スキーマ仕様書（JSON）から定義コードを生成する。

使い方:
    python3 tools/c2sql_gen.py specs/persons.json -o generated/

生成物（struct_name="persons" の例）:
    <out>/persons_schema.h   C構造体 typedef + COLS宣言 + 件数/最大件数マクロ + 登録ヘルパ宣言
    <out>/persons_schema.c   SqlRDBColumnDef[] 定義 + RegisterPersons()
    <out>/persons.cmake      生成物を STATIC ライブラリ化する CMake 断片

offset と size は offsetof / sizeof(((T*)0)->member) で機械的に埋めるため、
利用者・管理者は手入力しない（オフセット/サイズの取り違えを構造的に排除）。
"""
import argparse
import os
import sys

from c2sql_spec import SpecError, derive, load_spec, validate

BANNER = (
    "/* AUTO-GENERATED by tools/c2sql_gen.py from {src}. DO NOT EDIT.\n"
    " * Regenerate with: python3 tools/c2sql_gen.py {src} -o <dir>\n"
    " */\n"
)


def _struct_members(d):
    lines = []
    for c in d["cols"]:
        if c["arr_base"] is not None:        # text / blob → 固定長配列
            lines.append(f"    {c['arr_base']} {c['name']}[{c['size']}];")
        else:                                # int32 / int64 / real → スカラ
            lines.append(f"    {c['c_scalar']} {c['name']};")
    return "\n".join(lines)


def _col_rows(d):
    st = d["c_struct"]
    rows = []
    for c in d["cols"]:
        rows.append(
            f'    {{ "{c["name"]}", {c["sql_type"]}, '
            f"offsetof({st}, {c['name']}), "
            f"sizeof((({st} *)0)->{c['name']}), "
            f"{c['flags']} }},")
    return "\n".join(rows)


def render_header(d, src):
    guard = f"{d['macro_prefix']}_SCHEMA_H"
    return (
        BANNER.format(src=src)
        + f"#ifndef {guard}\n#define {guard}\n\n"
        '#include "c2sql.h"\n\n'
        "#include <stddef.h>\n#include <stdint.h>\n\n"
        "#ifdef __cplusplus\nextern \"C\" {\n#endif\n\n"
        f"typedef struct {d['c_struct']} {{\n{_struct_members(d)}\n}} {d['c_struct']};\n\n"
        f"#define {d['macro_prefix']}_COL_COUNT   {d['col_count']}u\n"
        f"#define {d['macro_prefix']}_MAX_RECORDS {d['max_records']}\n\n"
        f"/* Column definitions for table \"{d['table']}\" (deep-copied on register). */\n"
        f"extern const SqlRDBColumnDef {d['macro_prefix']}_COLS[{d['macro_prefix']}_COL_COUNT];\n\n"
        f"/* Register the \"{d['table']}\" schema (CREATE TABLE / schema check). */\n"
        f"SqlRDBResult {d['register_fn']}(SqlRDBHandle *h);\n\n"
        "#ifdef __cplusplus\n}\n#endif\n\n"
        f"#endif /* {guard} */\n"
    )


def render_source(d, src):
    return (
        BANNER.format(src=src)
        + f'#include "{d["table"]}_schema.h"\n\n'
        f"const SqlRDBColumnDef {d['macro_prefix']}_COLS[{d['macro_prefix']}_COL_COUNT] = {{\n"
        f"{_col_rows(d)}\n}};\n\n"
        f"SqlRDBResult {d['register_fn']}(SqlRDBHandle *h) {{\n"
        f'    return SqlRDBRegisterStruct(h, "{d["table"]}", '
        f"{d['macro_prefix']}_COLS, {d['macro_prefix']}_COL_COUNT);\n}}\n"
    )


def render_cmake(d, src):
    tgt = f"{d['table']}_schema"
    return (
        f"# AUTO-GENERATED by tools/c2sql_gen.py from {src}. DO NOT EDIT.\n"
        f"# include() this from your CMakeLists after the c2sql target is defined.\n"
        f"add_library({tgt} STATIC ${{CMAKE_CURRENT_LIST_DIR}}/{d['table']}_schema.c)\n"
        f"target_include_directories({tgt} PUBLIC ${{CMAKE_CURRENT_LIST_DIR}})\n"
        f"target_link_libraries({tgt} PUBLIC c2sql)\n"
    )


def generate(spec_path, out_dir):
    spec = load_spec(spec_path)
    validate(spec)
    d = derive(spec)
    src = os.path.basename(spec_path)
    os.makedirs(out_dir, exist_ok=True)

    artifacts = {
        f"{d['table']}_schema.h": render_header(d, src),
        f"{d['table']}_schema.c": render_source(d, src),
        f"{d['table']}.cmake": render_cmake(d, src),
    }
    written = []
    for name, content in artifacts.items():
        path = os.path.join(out_dir, name)
        with open(path, "w", encoding="utf-8") as fp:
            fp.write(content)
        written.append(path)
    return written


def main(argv):
    ap = argparse.ArgumentParser(description="c2sql code generator")
    ap.add_argument("spec", help="schema spec JSON (e.g. specs/persons.json)")
    ap.add_argument("-o", "--out", default="generated", help="output directory")
    args = ap.parse_args(argv[1:])

    try:
        written = generate(args.spec, args.out)
    except SpecError as exc:
        print(f"gen failed: {args.spec}", file=sys.stderr)
        for e in exc.errors:
            print(f"    - {e}", file=sys.stderr)
        return 1
    for p in written:
        print(f"generated {p}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
